"""Add calories and tags to items

Revision ID: f816cff3e0bf
Revises: df6d488fc016
Create Date: 2026-04-04 15:33:24.202094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f816cff3e0bf'
down_revision: Union[str, None] = 'df6d488fc016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
