"""add_enhanced_profile_fields

Revision ID: 2ef75f62bd2d
Revises: 0a987e4ccaf3
Create Date: 2026-04-04 18:30:38.479329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef75f62bd2d'
down_revision: Union[str, None] = '0a987e4ccaf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('our_story', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('opening_hours', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brand_accent_color', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('brand_accent_color')
        batch_op.drop_column('opening_hours')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('our_story')

    # ### end Alembic commands ###
